### ISSUE TITLE
Do not use Ubuntu

### ISSUE THREAD

**Issue by equwal** [dwilliamhouston/Calishot-2.0#12]
Use alpine in the docker image. No need to download many GB of Ubuntu bl0at.

**Comment by dwilliamhouston** [comment]
Will try again on this.  I tried this first time but had issues with getting python, pip3, and the other requirements installed.

**Comment by equwal** [comment]
https://github.com/dwilliamhouston/Calishot-2.0/pull/13
I fiexed it

**Comment by equwal** [comment]
plz pull

**Comment by dwilliamhouston** [comment]
I believe you missed the requirements.txt file install.

**Comment by equwal** [comment]
you don't need that because we used the extra flag thing in the pipx commands

**Comment by dwilliamhouston** [comment]
When I run it all the libraries in requirements.txt file are not loaded.  At least in my devcontainer

**Comment by equwal** [comment]
> When I run it all the libraries in requirements.txt file are not loaded. At least in my devcontainer

I went ahead and deleted requirements.txt so it shouldn't be an issue anymore. Please check out my pull's new force pushes.

**Comment by equwal** [comment]
pipx deals with this problem
